#ifndef CONSTANTS_H
#define CONSTANTS_H

#define LIM A0
#define LIM_READ_DELAY 500

#define STEPS_PER_REVOLUTION 2038

#define MAX_SPEED 60
#define MAX_STEPS_PER_SECOND 1000

#define DISTANCE 78.345
#define CIRCUMFERENCE PI * 10

#endif